version: '3.9'

services:

  angular:
    image: harbor.k8s.elab.rs/bolnica-1/frontend-angular:latest
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - my_local_network

networks:
  my_local_network:
    external: true