apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bolnica-1-ingress-frontend
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.domain }}
      secretName: dev-bolnica-1-certs
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: frontend
              port:
                number: 4200
